# SPDX-License-Identifier: MIT
---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint -c .yamllint.yml .
  ansible-lint
  flake8
platforms:
  - name: centos-6
    image: docker.io/linuxsystemroles/centos-6
    privileged: true
  - name: centos-7
    image: docker.io/linuxsystemroles/centos-7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../../tests/tests_default.yml
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - check
    - destroy
verifier:
  name: testinfra
