# SPDX-License-Identifier: MIT
---
- name: Set up bpftrace for use with PCP
  hosts: monitoring

  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_provider: pcp
        metrics_from_bpftrace: yes
