---
- hosts: analysis
  roles:
    - role: linux-system-roles.metrics
      vars:
        metrics_query_service: yes
        metrics_graph_service: yes
        metrics_monitored_hosts: ["app.example.com", "db.example.com"]
        metrics_retention_days: 10
