# SPDX-License-Identifier: MIT
---

- name: Set platform/version specific variables
  include_vars: "{{ item }}"
  loop:
    - "{{ role_path }}/vars/{{ ansible_facts['os_family'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  when: item is file

- name: Establish Elasticsearch metrics package names
  set_fact:
    __elasticsearch_packages_extra: "{{ __elasticsearch_packages_extra + __elasticsearch_packages_pcp }}"
  when:
    - elasticsearch_metrics_provider == 'pcp'
    - elasticsearch_agent|d(false)|bool

- name: Establish Elasticsearch metrics export package names
  set_fact:
    __elasticsearch_packages_extra: "{{ __elasticsearch_packages_extra + __elasticsearch_packages_export_pcp }}"
  when:
    - elasticsearch_metrics_provider == 'pcp'
    - elasticsearch_export_metrics|d(false)|bool

- name: Install needed Elasticsearch metrics packages
  package:
    name: "{{ __elasticsearch_packages_extra }}"
    state: present

- name: Ensure PCP Elasticsearch agent configuration directory exists
  file:
    path: "{{ __elasticsearch_conf_dir }}"
    state: directory
    mode: 0755
  when: elasticsearch_metrics_provider == 'pcp'

- name: Ensure PCP Elasticsearch agent is configured
  template:
    src: elasticsearch.conf.j2
    dest: "{{ __elasticsearch_conf }}"
    mode: 0600
  when:
    - elasticsearch_metrics_provider == 'pcp'
    - elasticsearch_agent|d(false)|bool

- name: Ensure PCP Elasticsearch export is running and enabled on boot
  service:
    name: pcp2elasticsearch
    state: started
    enabled: yes
  register: __pcp_elasticsearch_output
  failed_when: __pcp_elasticsearch_output.stdout is search('some string')
  when:
    - elasticsearch_metrics_provider == 'pcp'
    - elasticsearch_export_metrics|d(false)|bool

- name: debug
  debug:
    msg: es output {{ __pcp_elasticsearch_output | to_nice_json }}

- name: Ensure PCP Elasticsearch export is running and enabled on boot
  service:
    name: pcp2elasticsearch
    state: started
    enabled: yes
  ignore_errors: yes
  when:
    - elasticsearch_metrics_provider == 'pcp'
    - elasticsearch_export_metrics|d(false)|bool
