# yamllint disable rule:line-length
name: Sync ansible-pcp git subtree
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "42 1 * * *"
  workflow_dispatch:
jobs:
  subtree:
    runs-on: ubuntu-latest
    name: git subtree merge
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: subtree merge
        run: |
          set -euxo pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git subtree pull --prefix vendor/github.com/performancecopilot/ansible-pcp https://github.com/performancecopilot/ansible-pcp.git HEAD --squash
          git push
